# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(781, 679)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 141, 91))
        self.label.setStyleSheet("font-size:50px")
        self.label.setObjectName("label")
        self.userName = QtWidgets.QLineEdit(Dialog)
        self.userName.setGeometry(QtCore.QRect(440, 190, 151, 31))
        self.userName.setObjectName("userName")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(360, 180, 121, 51))
        self.label_2.setStyleSheet("font-size:20px;\n"
"font-family:\'宋体\'")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(360, 260, 81, 21))
        self.label_3.setStyleSheet("font-size:20px;\n"
"font-family:\'宋体\'")
        self.label_3.setObjectName("label_3")
        self.userPasswd = QtWidgets.QLineEdit(Dialog)
        self.userPasswd.setGeometry(QtCore.QRect(440, 250, 151, 31))
        self.userPasswd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.userPasswd.setObjectName("userPasswd")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(450, 100, 121, 51))
        self.label_5.setStyleSheet("font-size:25px;\n"
"font-family:\'宋体\'")
        self.label_5.setObjectName("label_5")
        self.LoginButton = QtWidgets.QPushButton(Dialog)
        self.LoginButton.setGeometry(QtCore.QRect(440, 320, 93, 28))
        self.LoginButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:宋体;\n"
"    /*字体大小为20点*/\n"
"    font-size:14pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:#f3704b;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#f15a22;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#f15a22;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"")
        self.LoginButton.setObjectName("LoginButton")
        self.registerButton = QtWidgets.QPushButton(Dialog)
        self.registerButton.setGeometry(QtCore.QRect(540, 290, 51, 21))
        self.registerButton.setStyleSheet("background-color:#ffffff;\n"
"    font-family:宋体;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:blue;")
        self.registerButton.setObjectName("registerButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "网盘"))
        self.label_2.setText(_translate("Dialog", "用户名："))
        self.label_3.setText(_translate("Dialog", "密码："))
        self.label_5.setText(_translate("Dialog", "登陆页面"))
        self.LoginButton.setText(_translate("Dialog", "登陆"))
        self.registerButton.setText(_translate("Dialog", "注册"))
