# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1416, 882)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 101, 71))
        self.label.setStyleSheet("font-size:50px")
        self.label.setObjectName("label")
        self.uploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadButton.setGeometry(QtCore.QRect(800, 10, 71, 31))
        self.uploadButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:宋体;\n"
"    /*字体大小为20点*/\n"
"    font-size:14pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:#f3704b;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#f15a22;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#f15a22;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"")
        self.uploadButton.setObjectName("uploadButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 1391, 451))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.fileTableLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.fileTableLayout.setContentsMargins(0, 0, 0, 0)
        self.fileTableLayout.setObjectName("fileTableLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 20, 121, 16))
        self.label_3.setObjectName("label_3")
        self.nowDirEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nowDirEdit.setGeometry(QtCore.QRect(370, 20, 231, 21))
        self.nowDirEdit.setText("")
        self.nowDirEdit.setObjectName("nowDirEdit")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 570, 1391, 261))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.downLoadLayout = QtWidgets.QVBoxLayout()
        self.downLoadLayout.setObjectName("downLoadLayout")
        self.horizontalLayout.addLayout(self.downLoadLayout)
        self.uploadLayout = QtWidgets.QVBoxLayout()
        self.uploadLayout.setObjectName("uploadLayout")
        self.horizontalLayout.addLayout(self.uploadLayout)
        self.showDownload = QtWidgets.QPushButton(self.centralwidget)
        self.showDownload.setGeometry(QtCore.QRect(20, 520, 201, 41))
        self.showDownload.setObjectName("showDownload")
        self.pasteButton = QtWidgets.QPushButton(self.centralwidget)
        self.pasteButton.setGeometry(QtCore.QRect(720, 10, 71, 31))
        self.pasteButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:宋体;\n"
"    /*字体大小为20点*/\n"
"    font-size:14pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:#f3704b;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#f15a22;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#f15a22;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"")
        self.pasteButton.setObjectName("pasteButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(610, 20, 101, 20))
        self.label_4.setObjectName("label_4")
        self.createFolderButton = QtWidgets.QPushButton(self.centralwidget)
        self.createFolderButton.setGeometry(QtCore.QRect(1270, 10, 131, 31))
        self.createFolderButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:宋体;\n"
"    /*字体大小为20点*/\n"
"    font-size:14pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:#f3704b;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#f15a22;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#f15a22;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"")
        self.createFolderButton.setObjectName("createFolderButton")
        self.newFolderName = QtWidgets.QLineEdit(self.centralwidget)
        self.newFolderName.setGeometry(QtCore.QRect(1140, 20, 113, 21))
        self.newFolderName.setObjectName("newFolderName")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1050, 20, 101, 20))
        self.label_5.setObjectName("label_5")
        self.folderUploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.folderUploadButton.setGeometry(QtCore.QRect(890, 10, 131, 31))
        self.folderUploadButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:宋体;\n"
"    /*字体大小为20点*/\n"
"    font-size:14pt;\n"
"    /*字体颜色为白色*/    \n"
"    color:white;\n"
"    /*背景颜色*/  \n"
"    background-color:#f3704b;\n"
"}\n"
"\n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#f15a22;\n"
"}\n"
"\n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color:#f15a22;\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"")
        self.folderUploadButton.setObjectName("folderUploadButton")
        self.hello = QtWidgets.QLabel(self.centralwidget)
        self.hello.setGeometry(QtCore.QRect(110, 20, 121, 16))
        self.hello.setText("")
        self.hello.setObjectName("hello")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1416, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "网盘"))
        self.uploadButton.setText(_translate("MainWindow", "上传"))
        self.label_3.setText(_translate("MainWindow", "当前文件夹路径："))
        self.showDownload.setText(_translate("MainWindow", "查看已经下载完成的文件"))
        self.pasteButton.setText(_translate("MainWindow", "粘贴"))
        self.label_4.setText(_translate("MainWindow", "在当前文件夹："))
        self.createFolderButton.setText(_translate("MainWindow", "新建文件夹"))
        self.label_5.setText(_translate("MainWindow", "新文件夹名："))
        self.folderUploadButton.setText(_translate("MainWindow", "文件夹上传"))
